//moving adjective list for further use
const adjectives = [

];

const dookieAdj = [
    'alcoholic',
    'ballsy',
    'badass',
    'bitchy',
    'bisexual',
    'bipolar',
    'busty',
    'crappy',
    'cunty',
    'communist',
    'capitalist',
    'cannibal',
    'christian',
    'damn',
    'damned',
    'drunk',
    'drugged',
    'erotic',
    'fascist',
    'feminist',
    'fisting',
    'farting',
    'farty',
    'fuckable',
    'fucking',
    'fucked',
    'gassy',
    'gay',
    'goddamn',
    'homosexual',
    'heterosexual',
    'hedonistic',
    'high',
    'kinky',
    'kickass',
    'lewd',
    'lecherous',
    'masculine',
    'mature',
    'masochistic',
    'mysogynistic',
    'moist',
    'naked',
    'nude',
    'naughty',
    'perverted',
    'polygamist',
    'pissed',
    'poopy',
    'racist',
    'religious',
    'republican',
    'sexy',
    'satanic',
    'sadistic',
    'straight',
    'slutty',
    'shitty',
    'xenophobic',

];